name: Deploy Hugo Site to Pages

on:
  push:
    paths-ignore:
      - "images/**"
      - "LICENSE"
      - "README.md"
    branches:
      - main
  workflow_dispatch:
    inputs:
      hugoVersion:
        description: "Hugo Version"
        required: false
        default: "0.112.4"

concurrency:
  group: "pages"
  cancel-in-progress: true

defaults:
  run:
    shell: bash

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: ${{ github.event.inputs.hugoVersion || '0.112.4' }}
    steps:
      - name: Install Hugo CLI
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_linux-amd64.deb \
          && sudo dpkg -i ${{ runner.temp }}/hugo.deb

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure Pages
        id: pages
        uses: actions/configure-pages@v3

      - name: Build with Hugo
        run: |
          hugo \
            --config hugo.toml \
            --environment production \
            --buildDrafts \
            --gc \
            --minify=true \
            --baseURL "${{ steps.pages.outputs.base_url }}"

      - name: Upload artifact for GitHub Pages
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: ./public

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2

      - name: Output deployed URL
        run: echo "Site deployed to: ${{ steps.deployment.outputs.page_url }}"
